#define EEPROM_Char_ADDRESS 0x0000
#define EEPROM_Char_DEFINITION "c"
#define EEPROM_Byte_ADDRESS 0x0001
#define EEPROM_Byte_DEFINITION "b"
#define EEPROM_Int_ADDRESS 0x0002
#define EEPROM_Int_DEFINITION "i"
#define EEPROM_Long_ADDRESS 0x0004
#define EEPROM_Long_DEFINITION "l"
#define EEPROM_Float_ADDRESS 0x0008
#define EEPROM_Float_DEFINITION "f"
#define EEPROM_String_ADDRESS 0x000c
#define EEPROM_String_DEFINITION "s"
#define EEPROM_Object_ADDRESS 0x001d
#define EEPROM_Object_DEFINITION "{cbilfs}"
#define EEPROM_ArrayOfInt_ADDRESS 0x003a
#define EEPROM_ArrayOfInt_DEFINITION "[i]"
#define EEPROM_ArrayOfInt_1_Definition_ADDRESS 0x003f
#define EEPROM_ArrayOfInt_1_Definition_DEFINITION "i"
#define EEPROM_ArrayOfInt_3_Definition_ADDRESS 0x0043
#define EEPROM_ArrayOfInt_3_Definition_DEFINITION "i"
#define EEPROM_ArrayOfObject_ADDRESS 0x0049
#define EEPROM_ArrayOfObject_DEFINITION "[{bisc}]"
#define EEPROM_ArrayOfObject_0_Object_ADDRESS 0x004c
#define EEPROM_ArrayOfObject_0_Object_DEFINITION "{bisc}"
#define EEPROM_ArrayOfObject_0_Object_Int8_ADDRESS 0x004f
#define EEPROM_ArrayOfObject_0_Object_Int8_DEFINITION "b"
#define EEPROM_ArrayOfObject_0_Object_Int16_ADDRESS 0x0050
#define EEPROM_ArrayOfObject_0_Object_Int16_DEFINITION "i"
#define EEPROM_ArrayOfObject_0_Object_String_ADDRESS 0x0052
#define EEPROM_ArrayOfObject_0_Object_String_DEFINITION "s"
#define EEPROM_ArrayOfObject_0_Object_Char_ADDRESS 0x0061
#define EEPROM_ArrayOfObject_0_Object_Char_DEFINITION "c"
#define EEPROM_ArrayOfObject_1_Object_ADDRESS 0x0062
#define EEPROM_ArrayOfObject_1_Object_DEFINITION "{bisc}"
